# An example YAML file
# This stores configurations in the projects working directory at staticfiles/.instrbuilder/config.yaml
# configurations: 
#   1) 'csv_directory' directory of the csv files (of commands)
#   2) 'cmd_name' name of the commands file 
#   3) 'lookup_name' name of the lookup file 
#   4) instrument details including name, python class, and address
csv_directory: C:\Users\denko\PSI\qc_website-main\staticfiles\instruments
cmd_name: commands.csv
lookup_name: lookup.csv
instruments:
  sx199:
    address:
      pyvisa: TCPIP::SX199::8888::SOCKET
    csv_folder: standford/sx199
    python_class: StandfordSX199
  sr830:
    address:
      pyvisa: TCPIP::SX199::8888::SOCKET
    csv_folder: standford/sr830
    python_class: StandfordSR830
