# An example YAML file
# This stores configurations in the user's home directory at ~/.instrbuilder/config.yaml
# configurations: 
#   1) 'csv_directory' directory of the csv files (of commands)
#   2) 'cmd_name' name of the commands file 
#   3) 'lookup_name' name of the lookup file 
#   4) instrument details including name, python class, and address
csv_directory: /Users/denko/PSI/psi-instrument-controller/instruments
cmd_name: commands.csv
lookup_name: lookup.csv
instruments:
  sx199:
    address:
      pyvisa: TCPIP::SX199::8888::SOCKET
#      pyvisa: USB0::0x2A8D::0x0101::MY57503303::INSTR
    csv_folder: standford/sx199
    python_class: StandfordSX199
