instruments:
  sx199:
    host: SX199
    port: 8888
  itc:
    host: itc-optistat.psi.ch
    port: 7020
  caylar:
    host: PUTE30DC28
    port: 1234
  toptica:
    host: 129.129.131.136
    port: 1234
  rfsoc:
    host: 129.129.131.103
    port: {}
    username: xilinx
    password: xilinx
  sr830:
    address: GPIB1::8::INSTR
